site_url: http://github.com/Garee/next-starter
display_url: http://github.com/Garee/next-starter
backend:
  name: git-gateway # test-repo https://www.netlifycms.org/docs/git-gateway-backend/
  branch: main
local_backend: true # https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
publish_mode: editorial_workflow
media_folder: public/images
public_folder: images
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about.json"
        fields:
          - { label: "Greeting", name: "greeting", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
  - name: "blog-post"
    label: "Blog Post"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
